Final modifications to notebook
datapartnership/niger-economic-monitoring pull request #28
Opened 2024-06-25 20:25 UTC by NenyeIfebirinachi

2024-06-25 21:03 UTC, g4brielvs commented
@NenyeIfebirinachi Many thanks for opening this PR. Is it ready for review?

2024-06-25 21:05 UTC, NenyeIfebirinachi commented
@g4brielvs Yes, it is.

2024-06-25 21:10 UTC, g4brielvs requested changes

2024-06-25 21:10 UTC, g4brielvs commented on data/conflictIndex_by_adm2.csv
@NenyeIfebirinachi Could you please clarify the data source and classification (e.g., Open, Official Use Only)?

2024-06-25 21:15 UTC, NenyeIfebirinachi commented on data/conflictIndex_by_adm2.csv
This is the secondary data I created using the ACLED conflict data and Niger boundary shapefile (Both are open). It contains the "conflict index" calculation and can be used by other collaborators for additional analysis on say for instance "conflict vs agriculture." 

It may be deleted, if need be, since they can also replicate the geometric mean calculation for conflict index using the original ACLED conflict data

2024-06-25 21:27 UTC, g4brielvs commented on data/conflictIndex_by_adm2.csv
Thank you for the clarification. It's often better not to version it directly on a GitHub repository for several reasons: data size, data updates, data security. Alternatively, you may archive the data file on [this location](https://worldbankgroup.sharepoint.com/:f:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Projects/Data%20Lab/Niger%20Economic%20Monitor?csf=1&web=1&e=jKrhMq) and update the documentation to reflect that.

2024-06-25 21:35 UTC, NenyeIfebirinachi commented on data/conflictIndex_by_adm2.csv
I just archived the data in the SharePoint folder and updated accordingly.

2024-06-25 21:40 UTC, NenyeIfebirinachi commented
Think I may have messed it up trying to update the PR. Please help.

2024-06-27 18:01 UTC, g4brielvs commented
Supersed by #31.

2024-06-27 18:01 UTC, closed without merging